from __future__ import annotations

from pathlib import Path

# Project paths
PROJECT_NAME = "pairs_trading"
SRC_DIR = Path(__file__).resolve().parents[1]
PROJECT_ROOT = SRC_DIR.parents[0]

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
INTERIM_DATA_DIR = DATA_DIR / "interim"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
UNIVERSE_DATA_DIR = DATA_DIR / "universe"
OUTPUTS_DIR = PROJECT_ROOT / "outputs"

# Default market/data settings
DEFAULT_START_DATE = "2022-03-01"
DEFAULT_END_DATE = "2023-03-31"
DEFAULT_INTERVAL_DAILY = "1d"
DEFAULT_INTERVAL_HOURLY = "1h"

# Pair selection thresholds
DEFAULT_PCA_VARIANCE_THRESHOLD = 0.80
DEFAULT_OPTICS_MIN_SAMPLES = 3
DEFAULT_COINTEGRATION_ALPHA = 0.10
DEFAULT_HURST_THRESHOLD = 0.50
DEFAULT_MIN_HALF_LIFE_DAYS = 1.0
DEFAULT_MAX_HALF_LIFE_DAYS = 365.0
DEFAULT_MIN_MEAN_CROSSES_PER_YEAR = 12.0

# Strategy defaults
DEFAULT_BOLLINGER_WINDOW = 20
DEFAULT_BOLLINGER_NUM_STD = 2.0
DEFAULT_BOLLINGER_EXIT_STD = 0.5

DEFAULT_OU_WINDOW = 20
DEFAULT_OU_CONFIDENCE = 0.98
DEFAULT_OU_N_PATHS = 20000
DEFAULT_OU_ENTRY_Z = 1.0
DEFAULT_OU_EXIT_Z = 0.2

DEFAULT_COPULA_ENTRY_QUANTILE = 0.15
DEFAULT_COPULA_EXIT_QUANTILE = 0.50

DEFAULT_COINTEGRATION_ENTRY_Z = 2.0
DEFAULT_COINTEGRATION_EXIT_Z = 0.5

# Backtest defaults
DEFAULT_INITIAL_CAPITAL = 100000.0
DEFAULT_NOTIONAL_PER_TRADE = 1.0
DEFAULT_TRANSACTION_COST_BPS = 1.0
DEFAULT_SLIPPAGE_BPS = 1.0
DEFAULT_PERIODS_PER_YEAR = 252

# Risk defaults
DEFAULT_MAX_PAIR_LOSS_PCT = 0.05
DEFAULT_MAX_PORTFOLIO_DRAWDOWN_PCT = 0.15
DEFAULT_PAIR_REFRESH_DAYS = 180
DEFAULT_FORECAST_REFRESH_DAYS = 5
DEFAULT_MAX_ALLOWED_PREDICTION_ERROR = 0.02
DEFAULT_RISK_FRACTION = 0.02